//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

#include <Arduino.h>


void user_setup();
void user_loop();



int16_t set_FREQUENCY(uint32_t);
int16_t set_PHASE(uint16_t);
int16_t set_DELTA(int16_t); 
int16_t set_TIMESTEP(int16_t);
int16_t call_RUN();
int16_t call_STOP();
int16_t set_VIBTIME(uint32_t);
int16_t set_SEEDINT(uint32_t);


#endif // inodriver_user_h