//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#include "inodriver_user.h"
#include "dephased_pwm.h"
#include "settings.h"
#include "vib_control.h"

DephasedPWM pwm;
VibrationControl vib(2);

volatile uint32_t delta = 0;

void TC5_Handler() {
  pwm.phase_loop(delta);
}

void user_setup() {

  pwm.init();
  vib.init();

  delta = 30;    // valor por defecto.

}

void user_loop() {
  vib.vibrator();
}


int16_t set_FREQUENCY(uint32_t frequency) {
  pwm.set_frequency(frequency);
  return 0;
}


int16_t set_PHASE(uint16_t phase) {
  pwm.set_phase(phase);
  return 0;
}

int16_t set_DELTA(int16_t _delta) {
  delta = _delta;
  return 0;
}


int16_t set_TIMESTEP(int16_t timestep) {
  pwm.set_timestep(timestep);
  return 0;
}



//int16_t call_PAUSE() {
//  dephased_pwm.pause();
//  return 0;
//}

int16_t set_VIBTIME(uint32_t vibtime) {
  vib.set_vibtime(vibtime);
  return 0;
}

int16_t set_SEEDINT(uint32_t interval) {
  vib.set_seedint(interval);
  return 0;
}

int16_t call_RUN() {
    vib.run(); 
    return 0;
}

int16_t call_STOP() {
    vib.stop(); 
    return 0;
}

int16_t set_vibrator_enabled(bool enabled) {
  if (enabled) {
    vib.run();
  } else {
    vib.stop();
  }
  return 0;
}