//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.867609
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);

void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperSet_FREQUENCY(); 
void wrapperSet_PHASE(); 
void wrapperSet_DELTA(); 
void wrapperSet_TIMESTEP();
//void wrapperCall_PAUSE();
void wrapperCall_RUN();
void wrapperCall_STOP();
void wrapperSet_SEEDINT();
void wrapperSet_VIBTIME();


#endif // inodriver_bridge_h