#ifndef SETTINGS_H
#define SETTINGS_H

#define DEFAULT_FREQ 40000
#define DEFAULT_PHASE 0
#define DEFAULT_DELTA 30
#define DEFAULT_TIMESTEP 40
#define DEFAULT_VIBTIME 35
#define DEFAULT_SEEDINT 1000

#endif